version: 2.1
orbs:
  node: circleci/node@1.1.6
executors:
  default-executor:
    docker:
      - image: circleci/node:12.15.0-stretch
jobs:
  build:
    executor: default-executor
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm ci
  deploy:
    executor: default-executor
    steps:
      - checkout
      - run: bash deploy.sh

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
