version: 2.1

# Use the official Node orb for reusable steps such as "node/with-cache"
orbs:
  node: circleci/node@1.1.6

# Define reusable executors to avoid duplicating in each job
executors:
  default-executor:
    docker:
      - image: circleci/node:12.15.0-stretch

# Define jobs
jobs:
  # Install dependencies and run tests
  build-and-test:
    executor: default-executor
    steps:
      - checkout
      # Run a set of steps with node dependencies cached, to speed up build times
      # https://circleci.com/orbs/registry/orb/circleci/node#commands-with-cache
      - node/with-cache:
          steps:
            - run: npm ci
      - run: npm test

  # Build Docker image and push to Docker Hub
  # Authenticate with Digital Ocean CLI and deploy app
  deploy:
    executor: default-executor
    steps:
      - checkout
      # Allow using Docker commands
      - setup_remote_docker
      - run: bash deploy.sh

# Run jobs from above in configurable sequences called workflows
workflows:
  version: 2
  # Workflow name
  build-deploy:
    jobs:
      - build-and-test
      - deploy:
          requires:
            # Run after all tests have passed
            - build-and-test
          filters:
            branches:
              # Only deploy on pushes to the master branch
              only: master
